version: "3.7"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  workspace:
    build:
      context: ${DOCKER_PATH_BIN}/workspace
      args:
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
    ports:
      - ${WORKSPACE_HTTP_PORT}:3032
      - ${WORKSPACE_SSH}:22
      - ${APP_BACKEND_PORT}:3009 # backend_adonis
      - ${APP_BACKEND_NESTJS_PORT}:3010 # backend_nest
      - ${APP_FRONTEND_PORT}:3011 # frontend_next
      - ${APP_ECOMMERCE_PORT}:3012 # ecommerce_next
      - ${APP_STORYBOOK_PORT}:6006 # storybook
    links:
      - postgres
    volumes:
      - ${DOCUMENT_ROOT}:/var/www
    networks:
      - backend

  nginx:
    build:
      context: ${DOCKER_PATH_BIN}/nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        # - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "${VARNISH_BACKEND_PORT}:81"
    networks:
      - frontend
      - backend

  mysql:
    image: "mysql:8.0"
    restart: 'always'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "${DB_MYSQL_DATABASE}"
      MYSQL_USER: "${DB_MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_PASSWORD}"
    ports:
      - "${DB_MYSQL_PORT}:3306"
    volumes:
      - ${DOCKER_PATH_DATA}/mysql:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    networks:
      - backend

  postgres:
    build: ${DOCKER_PATH_BIN}/postgres
    tty: true
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - ${DOCKER_PATH_DATA}/postgres:/var/lib/postgresql/data
      - ${DOCKER_PATH_LOG}/postgres:/var/log/postgresql
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DATABASE}
    networks:
      - backend

  backend_nest:
    build:
      context: .
      dockerfile: ./.docker/bin/backend-nest/Dockerfile 
      target: backend-nest-development
    networks:
      - backend
    ports:
    - 3010:3010

  pgadmin4:
    image: "dpage/pgadmin4"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN4_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN4_PASSWORD}
    ports:
      - "${PGADMIN4_PORT}:80"
    volumes:
      - ${DOCKER_PATH_DATA}/pgadmin4:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - ${DOCKER_PATH_DATA}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - backend

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - backend
