

name: CI - BUILD - FEAT/** BACKEND-NEST
on:  
  push: 
    branches:  
    - feat/**
    paths: 
      - packages/backend-nest/**

jobs: 
  build: 
    runs-on: ubuntu-latest 

    defaults: 
      run: 
        working-directory: packages/backend-nest 

    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v2 
        with: 
          fetch-depth: 0 
 
      - name: Setup Node 
        uses: actions/setup-node@v1 
        with: 
          node-version: 16.x.x 
 
      - name: Cache Yarn dependencies 
        uses: actions/cache@v1 
        with: 
          path: ~/.cache/yarn 
          key: ${{ runner.OS }}-yarn-${{ hashFiles(format('{0}-{1}', github.workspace, '/yarn.lock')) }} 
          restore-keys: | 
            ${{ runner.OS }}-yarn- 
   
      - name: Install dependencies 
        run: yarn install 
 
      - name: Check Lintings 
        run: yarn lint 
 
      # - name: Check Tests 
      #   run: yarn test 
 
      # - name: Check commit message 
      #   uses: wagoid/commitlint-github-action@v4 
 
      - name: Build Project 
        run: yarn build 
      

      # - name: Generate build number
      #   id: buildnumber
      #   uses: einaregilsson/build-number@v3 
      #   with:
      #     token: ${{ secrets.github_token }} 

      # - uses: actions/checkout@v2
      # - name: Login to Docker Hub
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      #   run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # - name: Setup up Docker Buildx      
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Buil and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with: 
      #     context: .
      #     file: ./.docker/bin/backend-nest/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-nest:${{ steps.buildnumber.outputs.build_number }}

